### PR TITLE
Added method to get Service Statuses and receive 'userproperties' and 'userid' in authentication

### PR DESCRIPTION
**Pull request by JBou**
Just created this Pull Request a few months ago, but it had errors. Now all should be fine, all errors have been fixed. 
This are some tasks from issue #214

### CODE REVIEW

**Comment by JBou** [comment]
Sorry, but i don't have any problems. For me all is working fine. How can i fix this problems?

**Comment by SirCmpwn** [comment]
A healthy dose of Google would be a good start. Look at the "Files changed" tab of this pull request to see the problem.

**Comment by JBou** [comment]
Should be fixed!

**Comment by SirCmpwn** [comment]
Thanks!

**Pull request merged**
